services:
  app:
    build: .
    ports:
      - "8984:8984"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1  # for python logging (but doesn't work right now)
    expose:
      - 8984
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ipc: host
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: gunicorn --bind 0.0.0.0:8984 --threads=16 --timeout 300 wsgi:app
